/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameadd;

import static java.awt.PageAttributes.MediaType.A;
import java.util.Scanner;

/**
 *
 * @author MAURYA
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public HOME() {
             initComponents();
          try{   a= (int) (Math.random()*100+1);
             b= (int) (Math.random()*100+1);
             gen = Integer.toString(a)+" + "+Integer.toString(b)+" =";
             A.setText(gen);
             sum=a+b;
          }
          catch(Exception e)
          {
            
          }
        
          
        
       // Mainfuntion();
        
    }
            String name ;
            int total=15;
            int trail=total;
             
            int correct = 0;
            int wrong = 0;
            String gen;
            int sum=0;
            int a=0 ;
            int b=0;
            int count=0;
            
         

    public void Mainfuntion(){
    
          try{ 
           if(txtValue.getText()!=null)
                  count = Integer.valueOf(txtValue.getText().trim());
            else
                  count=0;
             if(sum==count){
                  Status.setText("Good");
                  correct++;
                  Score.setText(Integer.toString(correct*10));
                  
             }
             else
             {  Status.setText("Poor");
                wrong++;
             }
                 
           
           
             
             a= (int) (Math.random()*100+1);
             b= (int) (Math.random()*100+1);
             gen = Integer.toString(a)+" + "+Integer.toString(b);
             A.setText(gen);
             sum=a+b;
           
            Correct.setText(Integer.toString(correct));
            Wrong.setText(Integer.toString(wrong));
          
            trail--;
           if(trail==0)
                   {
                     txtValue.setVisible(false);
                     Status.setText("Total Question \t"+Integer.toString(correct+wrong)+" \t\tAccuracy\t "+ Integer.toString((correct*100)/total)+" %");
                     A.setText(Integer.toString(correct)+"/"+Integer.toString(total));
                     
                     Score.setText(Integer.toString(correct*10));
                   }
    }
    catch(Exception e)
    {
    
    }
           
        
        
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtValue = new javax.swing.JTextField();
        A = new javax.swing.JLabel();
        Score = new javax.swing.JLabel();
        Wrong = new javax.swing.JLabel();
        Correct = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        status1 = new javax.swing.JLabel();
        status2 = new javax.swing.JLabel();
        Score1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Stop = new javax.swing.JButton();
        Restart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtValue.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        txtValue.setText("0");
        txtValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValueFocusLost(evt);
            }
        });
        txtValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueActionPerformed(evt);
            }
        });
        txtValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValueKeyReleased(evt);
            }
        });

        A.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        A.setText("jLabel1");

        Score.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Score.setText("Your Score ");

        Wrong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Wrong.setText("wrong");

        Correct.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Correct.setText("correct");

        Status.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Status.setText("correct/wrong");

        status1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        status1.setText("Wrong");

        status2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        status2.setText("Correct");

        Score1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Score1.setText("Courrent Score");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setText("ADDTION PRACTICS TOOL");

        Stop.setText("Stop");
        Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopActionPerformed(evt);
            }
        });

        Restart.setText("Restart");
        Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 99, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(status2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Correct))
                            .addComponent(A, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(txtValue)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Wrong))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Score1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Score)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(377, Short.MAX_VALUE)
                    .addComponent(Restart)
                    .addGap(48, 48, 48)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Score1)
                    .addComponent(Score))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status2)
                    .addComponent(Correct))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wrong))
                .addGap(18, 18, 18)
                .addComponent(Status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(287, Short.MAX_VALUE)
                    .addComponent(Restart, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueActionPerformed
       Mainfuntion(); 
       txtValue.setText("0");
        
       
       
       
    }//GEN-LAST:event_txtValueActionPerformed

    private void txtValueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValueKeyReleased
            
        // TODO add your handling c// TODO add your handling code here:
    }//GEN-LAST:event_txtValueKeyReleased

    private void txtValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValueFocusLost
        
   // TODO add your handling code here:
    }//GEN-LAST:event_txtValueFocusLost

    private void StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopActionPerformed
                     trail=0; 
                     
                    
                     Status.setText("Total Question \t"+Integer.toString(correct+wrong)+" \t\tAccuracy\t "+ Integer.toString((correct*100)/total)+" %");
                     A.setText(Integer.toString(correct)+"/"+Integer.toString(total));
                     
                     Score.setText(Integer.toString(correct*10));// TODO add your handling code here:
    }//GEN-LAST:event_StopActionPerformed

    private void RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartActionPerformed
     
            
            trail=total;
            correct = 0;
            wrong = 0;
            sum=0;
            a=0 ;
            b=0;
            count=0;
            Correct.setText(Integer.toString(correct));
            Wrong.setText(Integer.toString(wrong));
            txtValue.setVisible(true);
           
        // TODO add your handling code here:
    }//GEN-LAST:event_RestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel Correct;
    private javax.swing.JButton Restart;
    private javax.swing.JLabel Score;
    private javax.swing.JLabel Score1;
    private javax.swing.JLabel Status;
    private javax.swing.JButton Stop;
    private javax.swing.JLabel Wrong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel status1;
    private javax.swing.JLabel status2;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables

  
}
